### ISSUE TITLE
New GPT Submission: Ask Dr. Andrew Huberman

### ISSUE THREAD

**Issue by jyboy** [all-in-aigc/gpts-works#1]
*Name*: Ask Dr. Andrew Huberman
*Description*: Maximize your productivity, physical and mental health with neuroscience. Trained with all the podcast episodes from Huberman Lab.
*Link*: [chat.openai.com/g/g-1xC65osMP-ask-dr-andrew-huberman](https://chat.openai.com/g/g-1xC65osMP-ask-dr-andrew-huberman)

**Comment by idoubi** [comment]
moved to https://github.com/all-in-aigc/gpts-works/issues/5
