### ISSUE TITLE
Need GPTs Dataset? 

### ISSUE THREAD

**Issue by seadfeng** [all-in-aigc/gpts-works#14]
Free GPts Scraper from Apify
> Gets you GPTs data from Openai.
> Download your data as JSON, HTML Table, CSV, Execl, RSS Feed

https://apify.com/seadapp/free-gpts-scraper

**Sample data**
https://console.apify.com/view/runs/4d8OdhcKKT8SftO9q

**Comment by idoubi** [comment]
Thanks
