### ISSUE TITLE
大佬，请教一个问题关于浏览器插件项目

### ISSUE THREAD

**Issue by kill136** [all-in-aigc/gpts-works#24]
大佬，您好，我按照您的教程部署的时候，其他两个项目没有问题能跑起来，但是浏览器插件项目遇到一个问题，就是我直接http://localhost:8099/本地访问的时候，没有问题的，但是我换一个网站，再去访问插件就报错了，如下图
![1702014681181](https://github.com/all-in-aigc/gpts-works/assets/22001343/c8444843-e048-4cf3-96b4-2990c18c4aeb)
请问一下 如何修改呢

**Comment by idoubi** [comment]
Debug by searching Google or ChatGPT.
