### ISSUE TITLE
WINDOWS电脑需要先安装pnpm next 检查package.json：

### ISSUE THREAD

**Issue by CharlieLZ** [all-in-aigc/gpts-works#4]
对于make dev命令，您可能需要使用适合您项目的具体命令。make通常在Windows上不可用，除非您安装了GNU Make或类似工具。如果您的项目使用Node.js开发，并且有一个package.json文件，您可以查看其中的scripts部分，找到启动开发服务器的脚本命令。通常这可能是npm run dev或pnpm run dev

安装pnpm：
如果您没有安装pnpm，您需要先安装它。可以使用npm来安装pnpm。

cmd
Copy code
npm install -g pnpm
-g选项表示全局安装，这样pnpm命令可以在任何地方使用。

安装next：
错误 'next' 不是内部或外部命令 表示next.js可能没有正确安装。您可以尝试在您的项目文件夹内局部安装next.js：

cmd
Copy code
npm install next react react-dom
这会在您的项目的node_modules文件夹下安装next以及next所依赖的react和react-dom。

检查package.json：
确保您的package.json文件中有一个dev脚本指向next dev。它看起来应该像这样：

json
Copy code
"scripts": {
  "dev": "next dev",
  // ...其他脚本
}
运行开发服务器：
一旦next安装完成，并且package.json中有正确的脚本，您应该能够用以下命令启动开发服务器：

cmd
Copy code
npm run dev

**Comment by idoubi** [comment]
`make dev` is an alias command for `pnpm dev`
